### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by PsiACE**
Just bump deps.

cc @dalance , would you like to help review?

Signed-off-by: Chojan Shang <psiace@outlook.com>

### CODE REVIEW

**Comment by PsiACE** [comment]
Or you can review #48 by @max-m . It may be ok after re-running ci.

**Comment by PsiACE** [comment]
if merged, please publish a new version

**Comment by dalance** [comment]
LGTM. Thanks.

**Comment by PsiACE** [comment]
Thank you, maybe a new version can be released?

**Comment by dalance** [comment]
I released v0.4.2.

**Pull request merged**
