### PR TITLE
Add `--avoid-dev-deps` and `--avoid-build-deps`

### LINKED ISSUE #18: Separate licenses by normal/build/development dependencies
It would be great if cargo-license could separate between normal, build and development dependencies, because in most cases the latter two do not affect licensing of the resulting library. Current `cargo_metadata` should have the necessary information: https://docs.rs/cargo_metadata/0.8.0/cargo_metadata/enum.DependencyKind.html

### PR DESCRIPTION
**Pull request by qryxip**
Closes #18.

```diff
 cargo-license 0.4.0
 Cargo subcommand to see licenses of dependencies.

 USAGE:
     cargo license [FLAGS] [OPTIONS]

 FLAGS:
         --all-features        Activate all available features
     -a, --authors             Display crate authors
+        --avoid-build-deps    Exclude build dependencies
+        --avoid-dev-deps      Exclude development dependencies
     -d, --do-not-bundle       Output one license per line
     -h, --help                Prints help information
     -j, --json                Detailed output as JSON
         --no-deps             Output information only about the root package and don't fetch dependencies
     -t, --tsv                 Detailed output as tab-separated-values
     -V, --version             Prints version information

 OPTIONS:
         --current-dir <CURRENT_DIR>    Current directory of the cargo metadata process
         --features <FEATURE>...        Space-separated list of features to activate
         --manifest-path <PATH>         Path to Cargo.toml
         --color <WHEN>                 Coloring [possible values: auto, always, never]
```

### CODE REVIEW

**Comment by dalance** [comment]
Looks good to me, but I think `avoid` may not be general.
How about `--exclude-build-deps` / `--exclude-dev-deps`?

**Comment by dalance** [comment]
Additionally, this does not work on workspace.
How about the following code?

```diff
diff --git a/src/lib.rs b/src/lib.rs
index b2ede7d..cff2269 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -65,10 +65,11 @@ pub fn get_dependencies_from_cargo_lock(
     let connected = {
         let resolve = metadata.resolve.as_ref().expect("missing `resolve`");

-        let root = resolve
-            .root
-            .as_ref()
-            .with_context(|| "this is a virtual manifest")?;
+        let roots = if let Some(root) = resolve.root.as_ref() {
+            vec![root]
+        } else {
+            metadata.workspace_members.iter().collect()
+        };

         let deps = resolve
             .nodes
@@ -106,11 +107,14 @@ pub fn get_dependencies_from_cargo_lock(
                 .map(|cargo_metadata::NodeDep { pkg, .. }| pkg)
         };

-        let mut connected = iter::once(root).collect::<HashSet<_>>();
-        let stack = &mut neighbors(root).collect::<Vec<_>>();
-        while let Some(package_id) = stack.pop() {
-            if connected.insert(package_id) {
-                stack.extend(neighbors(package_id));
+        let mut connected = HashSet::new();
+        for root in roots {
+            connected.insert(root);
+            let stack = &mut neighbors(root).collect::<Vec<_>>();
+            while let Some(package_id) = stack.pop() {
+                if connected.insert(package_id) {
+                    stack.extend(neighbors(package_id));
+                }
             }
         }
         connected
```

**Comment by qryxip** [comment]
> `avoid` may not be general

I named them after Cargo's [`-Z --avoid-dev-deps`](https://doc.rust-lang.org/cargo/reference/unstable.html#avoid-dev-deps). I thought `--exclude-dev-deps` was confusable with `--workspace -p <SPEC>... --exclude <SPEC>...` options from basic Cargo commands.

> this does not work workspace

That's right. It should work for a virtual manifest.

**Comment by dalance** [comment]
I understand the `avoid` naming.
I'll merge this PR after resolving conflict.
Could you resolve?

**Comment by qryxip** [comment]
BTW, Should `proc_macro` crates be excluded too...?

**Comment by dalance** [comment]
Why do you think so?

**Comment by qryxip** [comment]
Because `proc_macro` crates just "output" ASTs and are not statically/dynamically linked to the output artifact. (IANAL)

https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput

**Comment by dalance** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#CanIUseGPLToolsForNF

> Some programs copy parts of themselves into the output for technical reasons—for example, Bison copies a standard parser program into its output file. In such cases, the copied text in the output is covered by the same license that covers it in the source code. Meanwhile, the part of the output which is derived from the program's input inherits the copyright status of the input.

https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput

> So the only way you have a say in the use of the output is if substantial parts of the output are copied (more or less) from text in your program. For instance, part of the output of Bison (see above) would be covered by the GNU GPL, if we had not made an exception in this specific case.

This seems to show the output may be affected by the proc-macro license if the output AST is derived from `quote!` of the proc-macro.
Some proc-macros may be more similar to compiler, if so, the output may not be affected.
I don't know the boundary.

**Comment by qryxip** [comment]
I understand. Either way we should probably add another option in another PR.

**Pull request merged**
